// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Agreement_DeliveryDays")]
	public class AgreementDeliveryDay
	{
		[Column("Id"         , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long   Id          { get; set; } // bigint
		[Column("DayOfWeek"                                                                                     )] public int    DayOfWeek   { get; set; } // int
		[Column("AgreementId", CanBeNull    = false                                                             )] public string AgreementId { get; set; } = null!; // nvarchar(12)

		#region Associations
		/// <summary>
		/// FK_Agreement_DeliveryDays_Agreement_AgreementId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(AgreementId), OtherKey = nameof(DataModel.Agreement.Id))]
		public Agreement Agreement { get; set; } = null!;
		#endregion
	}
}
