// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Agreement")]
	public class Agreement
	{
		[Column("Id"                                , CanBeNull = false, IsPrimaryKey = true)] public string         Id                                 { get; set; } = null!; // nvarchar(12)
		[Column("Status"                                                                    )] public int            Status                             { get; set; } // int
		[Column("Owner"                                                                     )] public int            Owner                              { get; set; } // int
		[Column("CreatedOn"                                                                 )] public DateTimeOffset CreatedOn                          { get; set; } // datetimeoffset(7)
		[Column("UpdatedOn"                                                                 )] public DateTimeOffset UpdatedOn                          { get; set; } // datetimeoffset(7)
		[Column("OrderDelayInHoursBeforeDeliveryDay"                                        )] public int            OrderDelayInHoursBeforeDeliveryDay { get; set; } // int
		[Column("SupplierId"                        , CanBeNull = false                     )] public string         SupplierId                         { get; set; } = null!; // nvarchar(12)
		[Column("CustomerId"                        , CanBeNull = false                     )] public string         CustomerId                         { get; set; } = null!; // nvarchar(12)
		[Column("CatalogId"                         , CanBeNull = false                     )] public string         CatalogId                          { get; set; } = null!; // nvarchar(12)
		[Column("FailureReason"                                                             )] public string?        FailureReason                      { get; set; } // nvarchar(max)

		#region Associations
		/// <summary>
		/// FK_Agreement_DeliveryDays_Agreement_AgreementId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AgreementDeliveryDay.AgreementId))]
		public IEnumerable<AgreementDeliveryDay> DeliveryDaysAgreementIds { get; set; } = null!;

		/// <summary>
		/// FK_Agreement_Customer_CustomerId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(CustomerId), OtherKey = nameof(DataModel.Customer.Id))]
		public Customer Customer { get; set; } = null!;

		/// <summary>
		/// FK_Agreement_Supplier_SupplierId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(SupplierId), OtherKey = nameof(DataModel.Supplier.Id))]
		public Supplier Supplier { get; set; } = null!;

		/// <summary>
		/// FK_Agreement_Catalog_CatalogId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(CatalogId), OtherKey = nameof(DataModel.Catalog.Id))]
		public Catalog Catalog { get; set; } = null!;
		#endregion
	}
}
