// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Catalog_Products")]
	public class CatalogProduct
	{
		[Column("CatalogId", CanBeNull = false, IsPrimaryKey = true, PrimaryKeyOrder = 0)] public string         CatalogId { get; set; } = null!; // nvarchar(12)
		[Column("ProductId", CanBeNull = false, IsPrimaryKey = true, PrimaryKeyOrder = 1)] public string         ProductId { get; set; } = null!; // nvarchar(12)
		[Column("UnitPrice"                                                             )] public decimal        UnitPrice { get; set; } // decimal(18, 2)
		[Column("CreatedOn"                                                             )] public DateTimeOffset CreatedOn { get; set; } // datetimeoffset(7)
		[Column("UpdatedOn"                                                             )] public DateTimeOffset UpdatedOn { get; set; } // datetimeoffset(7)

		#region Associations
		/// <summary>
		/// FK_Catalog_Products_Product_ProductId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(ProductId), OtherKey = nameof(DataModel.Product.Id))]
		public Product Product { get; set; } = null!;

		/// <summary>
		/// FK_Catalog_Products_Catalog_CatalogId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(CatalogId), OtherKey = nameof(DataModel.Catalog.Id))]
		public Catalog Catalog { get; set; } = null!;
		#endregion
	}
}
