// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Delivery_Adjustments")]
	public class DeliveryAdjustment
	{
		[Column("Id"                      , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long            Id                      { get; set; } // bigint
		[Column("Identifier"              , CanBeNull    = false                                                             )] public string          Identifier              { get; set; } = null!; // nvarchar(12)
		[Column("LineKind"                                                                                                   )] public int             LineKind                { get; set; } // int
		[Column("Reference"               , CanBeNull    = false                                                             )] public string          Reference               { get; set; } = null!; // nvarchar(20)
		[Column("Name"                    , CanBeNull    = false                                                             )] public string          Name                    { get; set; } = null!; // nvarchar(150)
		[Column("PriceInfo_UnitPrice"                                                                                        )] public decimal         PriceInfoUnitPrice      { get; set; } // decimal(18, 2)
		[Column("PriceInfo_WholeSalePrice"                                                                                   )] public decimal         PriceInfoWholeSalePrice { get; set; } // decimal(18, 2)
		[Column("PriceInfo_VatPrice"                                                                                         )] public decimal         PriceInfoVatPrice       { get; set; } // decimal(18, 2)
		[Column("PriceInfo_OnSalePrice"                                                                                      )] public decimal         PriceInfoOnSalePrice    { get; set; } // decimal(18, 2)
		[Column("Quantity"                                                                                                   )] public int             Quantity                { get; set; } // int
		[Column("Vat"                                                                                                        )] public decimal         Vat                     { get; set; } // decimal(18, 2)
		[Column("Order_Reference"                                                                                            )] public string?         OrderReference          { get; set; } // nvarchar(20)
		[Column("Order_PublishedOn"                                                                                          )] public DateTimeOffset? OrderPublishedOn        { get; set; } // datetimeoffset(7)
		[Column("CreatedOn"                                                                                                  )] public DateTimeOffset  CreatedOn               { get; set; } // datetimeoffset(7)
		[Column("DeliveryId"              , CanBeNull    = false                                                             )] public string          DeliveryId              { get; set; } = null!; // nvarchar(12)

		#region Associations
		/// <summary>
		/// FK_DeliveryAdjustment_Batches_Delivery_Adjustments_DeliveryAdjustmentId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(DeliveryAdjustmentBatch.DeliveryAdjustmentId))]
		public IEnumerable<DeliveryAdjustmentBatch> DeliveryAdjustmentBatchesDeliveryAdjustmentsDeliveryAdjustmentIds { get; set; } = null!;

		/// <summary>
		/// FK_Delivery_Adjustments_Delivery_DeliveryId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(DeliveryId), OtherKey = nameof(DataModel.Delivery.Id))]
		public Delivery Delivery { get; set; } = null!;
		#endregion
	}
}
