// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Invoice_Lines")]
	public class InvoiceLine
	{
		[Column("Id"                      , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long           Id                      { get; set; } // bigint
		[Column("Identifier"              , CanBeNull    = false                                                             )] public string         Identifier              { get; set; } = null!; // nvarchar(12)
		[Column("Name"                    , CanBeNull    = false                                                             )] public string         Name                    { get; set; } = null!; // nvarchar(150)
		[Column("PriceInfo_UnitPrice"                                                                                        )] public decimal        PriceInfoUnitPrice      { get; set; } // decimal(18, 2)
		[Column("PriceInfo_WholeSalePrice"                                                                                   )] public decimal        PriceInfoWholeSalePrice { get; set; } // decimal(18, 2)
		[Column("PriceInfo_VatPrice"                                                                                         )] public decimal        PriceInfoVatPrice       { get; set; } // decimal(18, 2)
		[Column("PriceInfo_OnSalePrice"                                                                                      )] public decimal        PriceInfoOnSalePrice    { get; set; } // decimal(18, 2)
		[Column("Quantity"                                                                                                   )] public int            Quantity                { get; set; } // int
		[Column("Vat"                                                                                                        )] public decimal        Vat                     { get; set; } // decimal(18, 2)
		[Column("Order_Reference"         , CanBeNull    = false                                                             )] public string         OrderReference          { get; set; } = null!; // nvarchar(20)
		[Column("Order_PublishedOn"                                                                                          )] public DateTimeOffset OrderPublishedOn        { get; set; } // datetimeoffset(7)
		[Column("Delivery_Reference"      , CanBeNull    = false                                                             )] public string         DeliveryReference       { get; set; } = null!; // nvarchar(20)
		[Column("Delivery_DeliveredOn"                                                                                       )] public DateTimeOffset DeliveryDeliveredOn     { get; set; } // datetimeoffset(7)
		[Column("CreatedOn"                                                                                                  )] public DateTimeOffset CreatedOn               { get; set; } // datetimeoffset(7)
		[Column("InvoiceId"               , CanBeNull    = false                                                             )] public string         InvoiceId               { get; set; } = null!; // nvarchar(12)

		#region Associations
		/// <summary>
		/// FK_Invoice_Lines_Invoice_InvoiceId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(InvoiceId), OtherKey = nameof(DataModel.Invoice.Id))]
		public Invoice Invoice { get; set; } = null!;
		#endregion
	}
}
