// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Order_Lines")]
	public class OrderLine
	{
		[Column("Identifier"              , CanBeNull = false, IsPrimaryKey = true, PrimaryKeyOrder = 1)] public string         Identifier              { get; set; } = null!; // nvarchar(12)
		[Column("OrderId"                 , CanBeNull = false, IsPrimaryKey = true, PrimaryKeyOrder = 0)] public string         OrderId                 { get; set; } = null!; // nvarchar(12)
		[Column("LineKind"                                                                             )] public int            LineKind                { get; set; } // int
		[Column("Reference"               , CanBeNull = false                                          )] public string         Reference               { get; set; } = null!; // nvarchar(20)
		[Column("Name"                    , CanBeNull = false                                          )] public string         Name                    { get; set; } = null!; // nvarchar(150)
		[Column("PriceInfo_UnitPrice"                                                                  )] public decimal        PriceInfoUnitPrice      { get; set; } // decimal(18, 2)
		[Column("PriceInfo_WholeSalePrice"                                                             )] public decimal        PriceInfoWholeSalePrice { get; set; } // decimal(18, 2)
		[Column("PriceInfo_VatPrice"                                                                   )] public decimal        PriceInfoVatPrice       { get; set; } // decimal(18, 2)
		[Column("PriceInfo_OnSalePrice"                                                                )] public decimal        PriceInfoOnSalePrice    { get; set; } // decimal(18, 2)
		[Column("Quantity"                                                                             )] public int            Quantity                { get; set; } // int
		[Column("Vat"                                                                                  )] public decimal        Vat                     { get; set; } // decimal(18, 2)
		[Column("CreatedOn"                                                                            )] public DateTimeOffset CreatedOn               { get; set; } // datetimeoffset(7)

		#region Associations
		/// <summary>
		/// FK_Order_Lines_Order_OrderId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(OrderId), OtherKey = nameof(DataModel.Order.Id))]
		public Order Order { get; set; } = null!;
		#endregion
	}
}
