# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      dotnet restore $(System.DefaultWorkingDirectory)/Sheaft.sln
      dotnet build $(System.DefaultWorkingDirectory)/Sheaft.sln -c Release --no-restore
      dotnet test $(System.DefaultWorkingDirectory)/Sheaft.sln -c Release --no-restore --no-build
      dotnet publish $(System.DefaultWorkingDirectory)/Sheaft.Web.Api/Sheaft.Web.Api.csproj -c Release --no-restore --no-build --output publish_output/Sheaft.Web.Api/release/
      dotnet publish $(System.DefaultWorkingDirectory)/Sheaft.Web.Jobs/Sheaft.Web.Jobs.csproj -c Release --no-restore --no-build --output publish_output/Sheaft.Web.Jobs/release/
      dotnet publish $(System.DefaultWorkingDirectory)/Sheaft.Web.Payment/Sheaft.Web.Payment.csproj -c Release --no-restore --no-build --output publish_output/Sheaft.Web.Payment/release/
      dotnet publish $(System.DefaultWorkingDirectory)/Sheaft.Web.Signalr/Sheaft.Web.Signalr.csproj -c Release --no-restore --no-build --output publish_output/Sheaft.Web.Signalr/release/
      dotnet publish $(System.DefaultWorkingDirectory)/Sheaft.Web.Manage/Sheaft.Web.Manage.csproj -c Release --no-restore --no-build --output publish_output/Sheaft.Web.Manage/release/
  - task: ArchiveFiles@2
    displayName: "Archive GRAPHQL"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Api/release"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Api/build$(Build.BuildId).zip"
  - task: DeleteFiles@1
    displayName: "Delete GRAPHQL NewRelic"
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Api/release/newrelic'
      Contents: '*'
  - task: ArchiveFiles@2
    displayName: "Archive GRAPHQL WithoutMonitoring"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Api/release"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Api/build$(Build.BuildId)-nomonitoring.zip"
  - task: PublishBuildArtifacts@1
    displayName: "Publish GRAPHQL"
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Api/build$(Build.BuildId).zip'
      artifactName: 'sheaft-graphql'
  - task: PublishBuildArtifacts@1
    displayName: "Publish GRAPHQL WithoutMonitoring"
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Api/build$(Build.BuildId)-nomonitoring.zip'
      artifactName: 'sheaft-graphql-nomonitoring'
  - task: ArchiveFiles@2
    displayName: "Archive JOBS"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Jobs/release"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Jobs/build$(Build.BuildId).zip"
  - task: DeleteFiles@1
    displayName: "Delete JOBS NewRelic"
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Jobs/release/newrelic'
      Contents: '*'
  - task: ArchiveFiles@2
    displayName: "Archive JOBS WithoutMonitoring"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Jobs/release"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Jobs/build$(Build.BuildId)-nomonitoring.zip"
  - task: PublishBuildArtifacts@1
    displayName: "Publish JOBS"
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Jobs/build$(Build.BuildId).zip'
      artifactName: 'sheaft-jobs'
  - task: PublishBuildArtifacts@1
    displayName: "Publish JOBS WithoutMonitoring"
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Jobs/build$(Build.BuildId)-nomonitoring.zip'
      artifactName: 'sheaft-jobs-nomonitoring'
  - task: ArchiveFiles@2
    displayName: "Archive PAYMENT"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Payment/release"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Payment/build$(Build.BuildId).zip"
  - task: DeleteFiles@1
    displayName: "Delete PAYMENT NewRelic"
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Payment/release/newrelic'
      Contents: '*'
  - task: ArchiveFiles@2
    displayName: "Archive PAYMENT WithoutMonitoring"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Payment/release"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Payment/build$(Build.BuildId)-nomonitoring.zip"
  - task: PublishBuildArtifacts@1
    displayName: "Publish PAYMENT"
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Payment/build$(Build.BuildId).zip'
      artifactName: 'sheaft-payment'
  - task: PublishBuildArtifacts@1
    displayName: "Publish PAYMENT WithoutMonitoring"
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Payment/build$(Build.BuildId)-nomonitoring.zip'
      artifactName: 'sheaft-payment-nomonitoring'
  - task: ArchiveFiles@2
    displayName: "Archive SIGNALR"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Signalr/release"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Signalr/build$(Build.BuildId).zip"
  - task: DeleteFiles@1
    displayName: "Delete SIGNALR NewRelic"
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Signalr/release/newrelic'
      Contents: '*'
  - task: ArchiveFiles@2
    displayName: "Archive SIGNALR WithoutMonitoring"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Signalr/release"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Signalr/build$(Build.BuildId)-nomonitoring.zip"
  - task: PublishBuildArtifacts@1
    displayName: "Publish SIGNALR"
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Signalr/build$(Build.BuildId).zip'
      artifactName: 'sheaft-signalr'
  - task: PublishBuildArtifacts@1
    displayName: "Publish SIGNALR WithoutMonitoring"
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Signalr/build$(Build.BuildId)-nomonitoring.zip'
      artifactName: 'sheaft-signalr-nomonitoring'
  - task: ArchiveFiles@2
    displayName: "Archive MANAGE"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Manage/release"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Manage/build$(Build.BuildId).zip"
  - task: DeleteFiles@1
    displayName: "Delete MANAGE NewRelic"
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Manage/release/newrelic'
      Contents: '*'
  - task: ArchiveFiles@2
    displayName: "Archive MANAGE WithoutMonitoring"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Manage/release"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Manage/build$(Build.BuildId)-nomonitoring.zip"
  - task: PublishBuildArtifacts@1
    displayName: "Publish MANAGE"
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Manage/build$(Build.BuildId).zip'
      artifactName: 'sheaft-manage'
  - task: PublishBuildArtifacts@1
    displayName: "Publish MANAGE WithoutMonitoring"
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.Manage/build$(Build.BuildId)-nomonitoring.zip'
      artifactName: 'sheaft-manage-nomonitoring'