trigger:
  branches:
    include:
      - master
 
pool:
  vmImage: 'ubuntu-latest'
  
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'sheaft/sheaft.jobs'
        command: 'buildAndPush'
        Dockerfile: '**/Sheaft.Web.Jobs/Dockerfile'
        buildContext: '.'
        tags: |
          dev-$(Build.SourceVersion)
          latest