trigger:
  batch: true
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          dotnet restore $(System.DefaultWorkingDirectory)/Sheaft.sln
          dotnet build $(System.DefaultWorkingDirectory)/Sheaft.sln -c Release --no-restore
          dotnet test $(System.DefaultWorkingDirectory)/Sheaft.sln -c Release --no-restore --no-build
          dotnet publish $(System.DefaultWorkingDirectory)/Sheaft.Web.PAYMENT/Sheaft.Web.PAYMENT.csproj -c Release --no-restore --no-build --output publish_output/Sheaft.Web.PAYMENT/   
    - task: ArchiveFiles@2
      displayName: "Archive PAYMENT"
      inputs:
        rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.PAYMENT"
        includeRootFolder: false
        archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.PAYMENT/build$(Build.BuildId).zip"
    - task: PublishBuildArtifacts@1
      displayName: "Publish PAYMENT"
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/Sheaft.Web.PAYMENT/build$(Build.BuildId).zip'
        artifactName: 'sheaft-payment'