trigger:
  branches:
    include:
      - master
 
pool:
  vmImage: 'ubuntu-latest'
  
stages:
- stage: Build
  displayName: Build Docker images
  jobs:  
  - job: Build
    displayName: Build and push Docker images
    steps:
    - task: Docker@2
      displayName: Build GraphQL Image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'sheaft/sheaft.graphql'
        command: 'buildAndPush'
        Dockerfile: '**/Sheaft.Web.Api/Dockerfile'
        buildContext: '.'
        tags: |
          dev-$(Build.SourceVersion)
          latest
    - task: Docker@2
      displayName: Build Jobs Image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'sheaft/sheaft.jobs'
        command: 'buildAndPush'
        Dockerfile: '**/Sheaft.Web.Jobs/Dockerfile'
        buildContext: '.'
        tags: |
          dev-$(Build.SourceVersion)
          latest
    - task: Docker@2
      displayName: Build Manage Image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'sheaft/sheaft.manage'
        command: 'buildAndPush'
        Dockerfile: '**/Sheaft.Web.Manage/Dockerfile'
        buildContext: '.'
        tags: |
          dev-$(Build.SourceVersion)
          latest
    - task: Docker@2
      displayName: Build Signalr Image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'sheaft/sheaft.signalr'
        command: 'buildAndPush'
        Dockerfile: '**/Sheaft.Web.Signalr/Dockerfile'
        buildContext: '.'
        tags: |
          dev-$(Build.SourceVersion)
          latest
    - task: Docker@2
      displayName: Build Payment Image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'sheaft/sheaft.payment'
        command: 'buildAndPush'
        Dockerfile: '**/Sheaft.Web.Payment/Dockerfile'
        buildContext: '.'
        tags: |
          dev-$(Build.SourceVersion)
          latest