//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheaft.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheaft.Localization.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ville est requise.
        /// </summary>
        internal static string Address_City_Required {
            get {
                return ResourceManager.GetString("Address_City_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse {0} n&apos;est plus disponible.
        /// </summary>
        internal static string Address_Gone {
            get {
                return ResourceManager.GetString("Address_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ligne d&apos;adresse est requise.
        /// </summary>
        internal static string Address_Line1_Required {
            get {
                return ResourceManager.GetString("Address_Line1_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse {0} est introuvable.
        /// </summary>
        internal static string Address_NotFound {
            get {
                return ResourceManager.GetString("Address_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code postal est requis.
        /// </summary>
        internal static string Address_Zipcode_Required {
            get {
                return ResourceManager.GetString("Address_Zipcode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accord.
        /// </summary>
        internal static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;accord ne peut pas être accepté, il n&apos;est pas en attente d&apos;acceptation.
        /// </summary>
        internal static string Agreement_CannotBeAccepted_NotInWaitingStatus {
            get {
                return ResourceManager.GetString("Agreement_CannotBeAccepted_NotInWaitingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;accord ne peut pas être annulé, il a déjà été annulé.
        /// </summary>
        internal static string Agreement_CannotBeCancelled_AlreadyCancelled {
            get {
                return ResourceManager.GetString("Agreement_CannotBeCancelled_AlreadyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;accord ne peut pas être annulé, il a déjà été refusé.
        /// </summary>
        internal static string Agreement_CannotBeCancelled_AlreadyRefused {
            get {
                return ResourceManager.GetString("Agreement_CannotBeCancelled_AlreadyRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;accord ne peut pas être refusé, il n&apos;est pas en attente d&apos;acceptation.
        /// </summary>
        internal static string Agreement_CannotBeRefused_NotInWaitingStatus {
            get {
                return ResourceManager.GetString("Agreement_CannotBeRefused_NotInWaitingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;accord {0} n&apos;est plus disponible.
        /// </summary>
        internal static string Agreement_Gone {
            get {
                return ResourceManager.GetString("Agreement_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;accord {0} est introuvable.
        /// </summary>
        internal static string Agreement_NotFound {
            get {
                return ResourceManager.GetString("Agreement_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;heure selectionnée pour l&apos;accord est introuvable dans les horaires disponibles.
        /// </summary>
        internal static string Agreement_SelectedHour_NotFoundInDeliveryOpeningHours {
            get {
                return ResourceManager.GetString("Agreement_SelectedHour_NotFoundInDeliveryOpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La requête reçue est invalide, veuillez rafraichir la page et réessayer votre demande..
        /// </summary>
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Société.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse de la société est requise.
        /// </summary>
        internal static string Company_Address_Required {
            get {
                return ResourceManager.GetString("Company_Address_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse email de contact est requis.
        /// </summary>
        internal static string Company_Email_Required {
            get {
                return ResourceManager.GetString("Company_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La société {0} n&apos;est plus disponible.
        /// </summary>
        internal static string Company_Gone {
            get {
                return ResourceManager.GetString("Company_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom de la société est requis.
        /// </summary>
        internal static string Company_Name_Required {
            get {
                return ResourceManager.GetString("Company_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La société {0} est introuvable.
        /// </summary>
        internal static string Company_NotFound {
            get {
                return ResourceManager.GetString("Company_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro de SIRET est requis.
        /// </summary>
        internal static string Company_Siret_Required {
            get {
                return ResourceManager.GetString("Company_Siret_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le tag spécifié pour la société est introuvable.
        /// </summary>
        internal static string Company_TagNotFound {
            get {
                return ResourceManager.GetString("Company_TagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro de TVA est requis.
        /// </summary>
        internal static string Company_Vat_Required {
            get {
                return ResourceManager.GetString("Company_Vat_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a été modifié(e) depuis votre dernière requête, veuillez rafraichir la page et réexecuter votre demande..
        /// </summary>
        internal static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La référence {0} existe déjà.
        /// </summary>
        internal static string CreateProduct_Reference_AlreadyExists {
            get {
                return ResourceManager.GetString("CreateProduct_Reference_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression impossible, le compte possède des commandes actives.
        /// </summary>
        internal static string DeleteUser_CannotBeDeleted_CompanyHasActiveOrders {
            get {
                return ResourceManager.GetString("DeleteUser_CannotBeDeleted_CompanyHasActiveOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression impossible, vous possédez des commandes actives.
        /// </summary>
        internal static string DeleteUser_CannotBeDeleted_HasActiveOrders {
            get {
                return ResourceManager.GetString("DeleteUser_CannotBeDeleted_HasActiveOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la suppression de l&apos;identité unifiée du compte : {0}.
        /// </summary>
        internal static string DeleteUser_Oidc_DeleteProfile_Error {
            get {
                return ResourceManager.GetString("DeleteUser_Oidc_DeleteProfile_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode de livraison.
        /// </summary>
        internal static string DeliveryMode {
            get {
                return ResourceManager.GetString("DeliveryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer le mode de livraison {0}, {1} accords actif sont rattachés (annuler les accords avant de pouvoir supprimer ce mode de livraison, ou contactez notre support).
        /// </summary>
        internal static string DeliveryMode_CannotRemove_With_Active_Agreements {
            get {
                return ResourceManager.GetString("DeliveryMode_CannotRemove_With_Active_Agreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mode de livraison {0} n&apos;est plus disponible.
        /// </summary>
        internal static string DeliveryMode_Gone {
            get {
                return ResourceManager.GetString("DeliveryMode_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La durée en heures du vérouillage de prise de commande avant la livraison ne peut pas être inférieur ou égal à {0}.
        /// </summary>
        internal static string DeliveryMode_LockOrderHoursBeforeDelivery_CannotBe_LowerThan {
            get {
                return ResourceManager.GetString("DeliveryMode_LockOrderHoursBeforeDelivery_CannotBe_LowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mode de livraison {0} est introuvable.
        /// </summary>
        internal static string DeliveryMode_NotFound {
            get {
                return ResourceManager.GetString("DeliveryMode_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Département.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le département {0} n&apos;est plus disponible.
        /// </summary>
        internal static string Department_Gone {
            get {
                return ResourceManager.GetString("Department_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le département {0} est introuvable.
        /// </summary>
        internal static string Department_NotFound {
            get {
                return ResourceManager.GetString("Department_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse email pour l&apos;enregistrement à la newsletter est invalide.
        /// </summary>
        internal static string EmailProvider_Newsletter_Email_Invalid {
            get {
                return ResourceManager.GetString("EmailProvider_Newsletter_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;enregistrement à la newsletter a échoué.
        /// </summary>
        internal static string EmailProvider_Newsletter_RegisterFailure {
            get {
                return ResourceManager.GetString("EmailProvider_Newsletter_RegisterFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;envoi d&apos;email a échoué.
        /// </summary>
        internal static string EmailProvider_SendEmail_Failure {
            get {
                return ResourceManager.GetString("EmailProvider_SendEmail_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur générique a été générée.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livraison attendue.
        /// </summary>
        internal static string ExpectedDelivery {
            get {
                return ResourceManager.GetString("ExpectedDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de livraison sélectionnée ne peut pas être antérieure à la date du jour.
        /// </summary>
        internal static string ExpectedDelivery_ExpectedDate_CannotBe_BeforeNow {
            get {
                return ResourceManager.GetString("ExpectedDelivery_ExpectedDate_CannotBe_BeforeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de livraison sélectionnée n&apos;est pas située dans les horaires disponibles du producteur.
        /// </summary>
        internal static string ExpectedDelivery_ExpectedDate_NotIn_DeliveryOpeningHours {
            get {
                return ResourceManager.GetString("ExpectedDelivery_ExpectedDate_NotIn_DeliveryOpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La livraison attendue {0} n&apos;est plus disponible.
        /// </summary>
        internal static string ExpectedDelivery_Gone {
            get {
                return ResourceManager.GetString("ExpectedDelivery_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La livraison attendue {0} est introuvable.
        /// </summary>
        internal static string ExpectedDelivery_NotFound {
            get {
                return ResourceManager.GetString("ExpectedDelivery_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;êtes pas autorisé a accéder à cette ressource.
        /// </summary>
        internal static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} n&apos;est plus accessible, elle a été supprimée.
        /// </summary>
        internal static string Gone {
            get {
                return ResourceManager.GetString("Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La génération du code de parainage a échouée.
        /// </summary>
        internal static string Identifier_SponsorCode_Error {
            get {
                return ResourceManager.GetString("Identifier_SponsorCode_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La génération de l&apos;identifiant unique a échouée.
        /// </summary>
        internal static string Identifier_Uuid_Error {
            get {
                return ResourceManager.GetString("Identifier_Uuid_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier d&apos;import de catalogue est invalide, il manque l&apos;onglet principal des produits..
        /// </summary>
        internal static string ImportProduct_Missing_Tab {
            get {
                return ResourceManager.GetString("ImportProduct_Missing_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom du produit est requis, ligne {0}.
        /// </summary>
        internal static string ImportProduct_Name_Required_Line {
            get {
                return ResourceManager.GetString("ImportProduct_Name_Required_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La référence du produit existe déjà, ligne {0}.
        /// </summary>
        internal static string ImportProduct_Reference_AlreadyExists {
            get {
                return ResourceManager.GetString("ImportProduct_Reference_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le taux de TVA du produit est invalide, ligne {0}.
        /// </summary>
        internal static string ImportProduct_Vat_Invalid_Line {
            get {
                return ResourceManager.GetString("ImportProduct_Vat_Invalid_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prix HT du produit est invalide, ligne {0}.
        /// </summary>
        internal static string ImportProduct_WholeSalePrice_Invalid_Line {
            get {
                return ResourceManager.GetString("ImportProduct_WholeSalePrice_Invalid_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tâche.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seule une tâche échouée, terminée ou annulée peut être archivée.
        /// </summary>
        internal static string Job_CannotArchive_NotIn_TerminatedStatus {
            get {
                return ResourceManager.GetString("Job_CannotArchive_NotIn_TerminatedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;annuler la tâche, elle a déjà été annulée.
        /// </summary>
        internal static string Job_CannotCancel_AlreadyCancelled {
            get {
                return ResourceManager.GetString("Job_CannotCancel_AlreadyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;annuler la tâche, elle est déjà terminée.
        /// </summary>
        internal static string Job_CannotCancel_AlreadyDone {
            get {
                return ResourceManager.GetString("Job_CannotCancel_AlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de terminer la tâche, elle n&apos;est pas en cours de traitement.
        /// </summary>
        internal static string Job_CannotComplete_NotIn_ProcessingStatus {
            get {
                return ResourceManager.GetString("Job_CannotComplete_NotIn_ProcessingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de passer la tâche en échouée, elle a déjà été annulée.
        /// </summary>
        internal static string Job_CannotFail_AlreadyCancelled {
            get {
                return ResourceManager.GetString("Job_CannotFail_AlreadyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de passer la tâche en échouée, elle est déjà terminée.
        /// </summary>
        internal static string Job_CannotFail_AlreadyDone {
            get {
                return ResourceManager.GetString("Job_CannotFail_AlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de mettre en pause la tâche, elle n&apos;est pas en cours de traitement.
        /// </summary>
        internal static string Job_CannotPause_NotIn_ProcessingStatus {
            get {
                return ResourceManager.GetString("Job_CannotPause_NotIn_ProcessingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de reprendre la tâche, elle n&apos;est pas en pause.
        /// </summary>
        internal static string Job_CannotResume_NotIn_PausedStatus {
            get {
                return ResourceManager.GetString("Job_CannotResume_NotIn_PausedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de ré-éxecuter la tâche, elle n&apos;est pas annulée ou échouée.
        /// </summary>
        internal static string Job_CannotRetry_NotIn_CanncelledOrFailedStatus {
            get {
                return ResourceManager.GetString("Job_CannotRetry_NotIn_CanncelledOrFailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La commande pour la tâche est requise.
        /// </summary>
        internal static string Job_Command_Required {
            get {
                return ResourceManager.GetString("Job_Command_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tâche {0} n&apos;est plus disponible.
        /// </summary>
        internal static string Job_Gone {
            get {
                return ResourceManager.GetString("Job_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom de la tâche est requis.
        /// </summary>
        internal static string Job_Name_Required {
            get {
                return ResourceManager.GetString("Job_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tâche {0} est introuvable.
        /// </summary>
        internal static string Job_NotFound {
            get {
                return ResourceManager.GetString("Job_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La nom de la file de traitement est requis.
        /// </summary>
        internal static string Job_Queue_Required {
            get {
                return ResourceManager.GetString("Job_Queue_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur de la tâche est requis.
        /// </summary>
        internal static string Job_User_Required {
            get {
                return ResourceManager.GetString("Job_User_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le niveau {0} n&apos;est plus disponible.
        /// </summary>
        internal static string Level_Gone {
            get {
                return ResourceManager.GetString("Level_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom du niveau est requis.
        /// </summary>
        internal static string Level_Name_Required {
            get {
                return ResourceManager.GetString("Level_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le niveau {0} est introuvable.
        /// </summary>
        internal static string Level_NotFound {
            get {
                return ResourceManager.GetString("Level_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} est actuellement vérouillé(e).
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} est introuvable.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La notification {0} n&apos;est plus disponible.
        /// </summary>
        internal static string Notification_Gone {
            get {
                return ResourceManager.GetString("Notification_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La notification {0} est introuvable.
        /// </summary>
        internal static string Notification_NotFound {
            get {
                return ResourceManager.GetString("Notification_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le contenu de la notification est requis.
        /// </summary>
        internal static string Notification_Require_Content {
            get {
                return ResourceManager.GetString("Notification_Require_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consigne.
        /// </summary>
        internal static string Packaging {
            get {
                return ResourceManager.GetString("Packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La consigne {0} n&apos;est plus disponible.
        /// </summary>
        internal static string Packaging_Gone {
            get {
                return ResourceManager.GetString("Packaging_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom de la consigne est requis.
        /// </summary>
        internal static string Packaging_Name_Required {
            get {
                return ResourceManager.GetString("Packaging_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La consigne {0} est introuvable.
        /// </summary>
        internal static string Packaging_NotFound {
            get {
                return ResourceManager.GetString("Packaging_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La TVA de la consigne ne peut pas être supérieur à {0}%.
        /// </summary>
        internal static string Packaging_Vat_CannotBe_GreaterThan {
            get {
                return ResourceManager.GetString("Packaging_Vat_CannotBe_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La TVA de la consigne ne peut pas être inférieur à {0}%.
        /// </summary>
        internal static string Packaging_Vat_CannotBe_LowerThan {
            get {
                return ResourceManager.GetString("Packaging_Vat_CannotBe_LowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prix HT de la consigne ne peut pas être inférieur ou égal à {0}%.
        /// </summary>
        internal static string Packaging_WholeSalePrice_CannotBe_LowerThan {
            get {
                return ResourceManager.GetString("Packaging_WholeSalePrice_CannotBe_LowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produit.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez déjà noté ce produit.
        /// </summary>
        internal static string Product_CannotRate_AlreadyRated {
            get {
                return ResourceManager.GetString("Product_CannotRate_AlreadyRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La description du produit est trop longue, elle ne peut pas dépasser {0} caractères.
        /// </summary>
        internal static string Product_Description_TooLong {
            get {
                return ResourceManager.GetString("Product_Description_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le produit {0} n&apos;est plus disponible.
        /// </summary>
        internal static string Product_Gone {
            get {
                return ResourceManager.GetString("Product_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom du produit est requis.
        /// </summary>
        internal static string Product_Name_Required {
            get {
                return ResourceManager.GetString("Product_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le produit {0} est introuvable.
        /// </summary>
        internal static string Product_NotFound {
            get {
                return ResourceManager.GetString("Product_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le producteur est requis.
        /// </summary>
        internal static string Product_Producer_Required {
            get {
                return ResourceManager.GetString("Product_Producer_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La quantité par unité du produit ne peut pas être inférieur ou égale à {0}.
        /// </summary>
        internal static string Product_QuantityPerUnit_CannotBe_LowerOrEqualThan {
            get {
                return ResourceManager.GetString("Product_QuantityPerUnit_CannotBe_LowerOrEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La référence du produit est requise.
        /// </summary>
        internal static string Product_Reference_Required {
            get {
                return ResourceManager.GetString("Product_Reference_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le tag spécifié pour le produit est introuvable.
        /// </summary>
        internal static string Product_TagNotFound {
            get {
                return ResourceManager.GetString("Product_TagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le taux de TVA du produit ne peut pas être supérieur à {0}%.
        /// </summary>
        internal static string Product_Vat_CannotBe_GreaterThan {
            get {
                return ResourceManager.GetString("Product_Vat_CannotBe_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le taux de TVA du produit ne peut pas être inférieur à {0}%.
        /// </summary>
        internal static string Product_Vat_CannotBe_LowerThan {
            get {
                return ResourceManager.GetString("Product_Vat_CannotBe_LowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le poids du produit ne peut pas être inférieur ou égale à {0}kg.
        /// </summary>
        internal static string Product_Weight_CannotBe_LowerOrEqualThan {
            get {
                return ResourceManager.GetString("Product_Weight_CannotBe_LowerOrEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prix HT du produit ne peut pas être inférieur ou égal à {0}€.
        /// </summary>
        internal static string Product_WholeSalePrice_CannotBe_LowerOrEqualThan {
            get {
                return ResourceManager.GetString("Product_WholeSalePrice_CannotBe_LowerOrEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commande.
        /// </summary>
        internal static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;accepter la commande, elle n&apos;est pas en attente d&apos;acceptation.
        /// </summary>
        internal static string PurchaseOrder_CannotAccept_NotIn_WaitingStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotAccept_NotIn_WaitingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter le produit à la commande, elle est en cours de traitement.
        /// </summary>
        internal static string PurchaseOrder_CannotAddProduct_NotIn_WaitingStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotAddProduct_NotIn_WaitingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter le produit à la commande, il est introuvable.
        /// </summary>
        internal static string PurchaseOrder_CannotAddProduct_Product_NotFound {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotAddProduct_Product_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;annuler la commande, elle a déjà été livrée.
        /// </summary>
        internal static string PurchaseOrder_CannotCancel_AlreadyIn_DeliveredStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotCancel_AlreadyIn_DeliveredStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;annuler la commande, elle a déjà été refusée.
        /// </summary>
        internal static string PurchaseOrder_CannotCancel_AlreadyIn_RefusedStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotCancel_AlreadyIn_RefusedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier la quantité du produit de la commande, elle est en cours de traitement.
        /// </summary>
        internal static string PurchaseOrder_CannotChangeProductQuantity_NotIn_WaitingStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotChangeProductQuantity_NotIn_WaitingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier la quantité du produit de la commande, il est introuvable.
        /// </summary>
        internal static string PurchaseOrder_CannotChangeProductQuantity_Product_NotFound {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotChangeProductQuantity_Product_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de compléter la commande, elle n&apos;est pas en cours de traitement.
        /// </summary>
        internal static string PurchaseOrder_CannotComplete_NotIn_ProcessingStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotComplete_NotIn_ProcessingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de délivrer la commande, elle n&apos;est pas prête ou pas encore en cours de livraison.
        /// </summary>
        internal static string PurchaseOrder_CannotDeliver_NotIn_CompletedOrShippingStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotDeliver_NotIn_CompletedOrShippingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de refuser la commande, elle a déjà été annulée.
        /// </summary>
        internal static string PurchaseOrder_CannotRefuse_AlreadyIn_CancelledStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotRefuse_AlreadyIn_CancelledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de refuser la commande, elle a déjà été livrée.
        /// </summary>
        internal static string PurchaseOrder_CannotRefuse_AlreadyIn_DeliveredStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotRefuse_AlreadyIn_DeliveredStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de refuser la commande, elle a déjà été refusée.
        /// </summary>
        internal static string PurchaseOrder_CannotRefuse_AlreadyIn_RefusedStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotRefuse_AlreadyIn_RefusedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer le produit de la commande, elle est en cours de traitement.
        /// </summary>
        internal static string PurchaseOrder_CannotRemoveProduct_NotIn_WaitingStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotRemoveProduct_NotIn_WaitingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer le produit de la commande, il est introuvable.
        /// </summary>
        internal static string PurchaseOrder_CannotRemoveProduct_Product_NotFound {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotRemoveProduct_Product_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de débuter la livraison de la commande, elle n&apos;est pas prête.
        /// </summary>
        internal static string PurchaseOrder_CannotShip_NotIn_CompletedStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotShip_NotIn_CompletedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La commande {0} n&apos;est plus disponible.
        /// </summary>
        internal static string PurchaseOrder_Gone {
            get {
                return ResourceManager.GetString("PurchaseOrder_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La commande {0} est introuvable.
        /// </summary>
        internal static string PurchaseOrder_NotFound {
            get {
                return ResourceManager.GetString("PurchaseOrder_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier la quantité du produit de la commande, la quantité ne peut pas être inférieur ou égale à {0}.
        /// </summary>
        internal static string PurchaseOrder_ProductQuantity_CannotBe_LowerOrEqualThan {
            get {
                return ResourceManager.GetString("PurchaseOrder_ProductQuantity_CannotBe_LowerOrEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La référence de commande est requise.
        /// </summary>
        internal static string PurchaseOrder_Reference_Required {
            get {
                return ResourceManager.GetString("PurchaseOrder_Reference_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le client de la commande est requis.
        /// </summary>
        internal static string PurchaseOrder_Sender_Required {
            get {
                return ResourceManager.GetString("PurchaseOrder_Sender_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le vendeur de la commande est requis.
        /// </summary>
        internal static string PurchaseOrder_Vendor_Required {
            get {
                return ResourceManager.GetString("PurchaseOrder_Vendor_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commande rapide.
        /// </summary>
        internal static string QuickOrder {
            get {
                return ResourceManager.GetString("QuickOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter le produit à la commande rapide, il est déjà présent.
        /// </summary>
        internal static string QuickOrder_CannotAddProduct_Product_AlreadyIn {
            get {
                return ResourceManager.GetString("QuickOrder_CannotAddProduct_Product_AlreadyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer le produit de la commande rapide, il est introuvable.
        /// </summary>
        internal static string QuickOrder_CannotRemoveProduct_Product_NotFound {
            get {
                return ResourceManager.GetString("QuickOrder_CannotRemoveProduct_Product_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La commande rapide {0} n&apos;est plus disponible.
        /// </summary>
        internal static string QuickOrder_Gone {
            get {
                return ResourceManager.GetString("QuickOrder_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom de la commande rapide est requis.
        /// </summary>
        internal static string QuickOrder_Name_Required {
            get {
                return ResourceManager.GetString("QuickOrder_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La commande rapide {0} n&apos;est plus disponible.
        /// </summary>
        internal static string QuickOrder_NotFound {
            get {
                return ResourceManager.GetString("QuickOrder_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier la quantité du produit de la commande rapide, elle ne peut pas être inférieur ou égale à {0}.
        /// </summary>
        internal static string QuickOrder_ProductQuantity_CannotBe_LowerOrEqualThan {
            get {
                return ResourceManager.GetString("QuickOrder_ProductQuantity_CannotBe_LowerOrEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur de la commande rapide est requis.
        /// </summary>
        internal static string QuickOrder_User_Required {
            get {
                return ResourceManager.GetString("QuickOrder_User_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notation.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La note ne peut être supérieur à {0}.
        /// </summary>
        internal static string Rating_CannotBe_GreatherThan {
            get {
                return ResourceManager.GetString("Rating_CannotBe_GreatherThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La note ne peut être inférieur ou égale à {0}.
        /// </summary>
        internal static string Rating_CannotBe_LowerThan {
            get {
                return ResourceManager.GetString("Rating_CannotBe_LowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La notation {0} n&apos;est plus disponible.
        /// </summary>
        internal static string Rating_Gone {
            get {
                return ResourceManager.GetString("Rating_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La notation {0} est introuvable.
        /// </summary>
        internal static string Rating_NotFound {
            get {
                return ResourceManager.GetString("Rating_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur de la note est requis.
        /// </summary>
        internal static string Rating_User_Required {
            get {
                return ResourceManager.GetString("Rating_User_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Région.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La région {0} n&apos;est plus disponible.
        /// </summary>
        internal static string Region_Gone {
            get {
                return ResourceManager.GetString("Region_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La région {0} est introuvable.
        /// </summary>
        internal static string Region_NotFound {
            get {
                return ResourceManager.GetString("Region_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un compte profesionnel ne peut pas être magasin et producteur en même temps.
        /// </summary>
        internal static string RegisterCompany_CannotContains_ProducerAndStoreRoles {
            get {
                return ResourceManager.GetString("RegisterCompany_CannotContains_ProducerAndStoreRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de l&apos;association du compte à l&apos;identité unifiée : {0}.
        /// </summary>
        internal static string RegisterConsumer_Oidc_Register_Error {
            get {
                return ResourceManager.GetString("RegisterConsumer_Oidc_Register_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un compte existe déjà avec l&apos;adresse email renseignée.
        /// </summary>
        internal static string RegisterConsumer_User_AlreadyExists {
            get {
                return ResourceManager.GetString("RegisterConsumer_User_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code parain spécifié pour la création du compte est introuvable.
        /// </summary>
        internal static string RegisterConsumer_UserWithSponsorCode_NotFound {
            get {
                return ResourceManager.GetString("RegisterConsumer_UserWithSponsorCode_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de l&apos;association du compte à l&apos;identité unifiée : {0}.
        /// </summary>
        internal static string RegisterOwner_Oidc_Register_Error {
            get {
                return ResourceManager.GetString("RegisterOwner_Oidc_Register_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un compte existe déjà avec l&apos;adresse email renseignée.
        /// </summary>
        internal static string RegisterOwner_User_AlreadyExists {
            get {
                return ResourceManager.GetString("RegisterOwner_User_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le compte ne peut pas être un magasin et un producteur en même temps.
        /// </summary>
        internal static string RegisterOwner_User_CannotBe_ProducerAndStoreRoles {
            get {
                return ResourceManager.GetString("RegisterOwner_User_CannotBe_ProducerAndStoreRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code parain spécifié pour la création du compte professionel est introuvable.
        /// </summary>
        internal static string RegisterOwner_UserWithSponsorCode_NotFound {
            get {
                return ResourceManager.GetString("RegisterOwner_UserWithSponsorCode_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Récompense.
        /// </summary>
        internal static string Reward {
            get {
                return ResourceManager.GetString("Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La récompense {0} n&apos;est plus disponible.
        /// </summary>
        internal static string Reward_Gone {
            get {
                return ResourceManager.GetString("Reward_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom de la récompense est requis.
        /// </summary>
        internal static string Reward_Name_Required {
            get {
                return ResourceManager.GetString("Reward_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La récompense {0} est introuvable.
        /// </summary>
        internal static string Reward_NotFound {
            get {
                return ResourceManager.GetString("Reward_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parainage.
        /// </summary>
        internal static string Sponsoring {
            get {
                return ResourceManager.GetString("Sponsoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le parainage {0} n&apos;est plus disponible.
        /// </summary>
        internal static string Sponsoring_Gone {
            get {
                return ResourceManager.GetString("Sponsoring_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le parainage {0} est introuvable.
        /// </summary>
        internal static string Sponsoring_NotFound {
            get {
                return ResourceManager.GetString("Sponsoring_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le parrain est requis.
        /// </summary>
        internal static string Sponsoring_Sponsor_Required {
            get {
                return ResourceManager.GetString("Sponsoring_Sponsor_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le parrainé est requis.
        /// </summary>
        internal static string Sponsoring_Sponsored_Required {
            get {
                return ResourceManager.GetString("Sponsoring_Sponsored_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le tag {0} n&apos;est plus disponible.
        /// </summary>
        internal static string Tag_Gone {
            get {
                return ResourceManager.GetString("Tag_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom du tag est requis.
        /// </summary>
        internal static string Tag_Name_Required {
            get {
                return ResourceManager.GetString("Tag_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le tag {0} est introuvable.
        /// </summary>
        internal static string Tag_NotFound {
            get {
                return ResourceManager.GetString("Tag_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plage horaire.
        /// </summary>
        internal static string TimeSlot {
            get {
                return ResourceManager.GetString("TimeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;heure de début ne peut pas être supérieur ou égale à {0} heures.
        /// </summary>
        internal static string TimeSlot_From_CannotBe_GreaterOrEqualThan {
            get {
                return ResourceManager.GetString("TimeSlot_From_CannotBe_GreaterOrEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;heure de début ne peut pas être supérieur ou égale à l&apos;heure de fin.
        /// </summary>
        internal static string TimeSlot_From_CannotBe_GreaterOrEqualThan_To {
            get {
                return ResourceManager.GetString("TimeSlot_From_CannotBe_GreaterOrEqualThan_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La plage horaire {0} n&apos;est plus disponible.
        /// </summary>
        internal static string TimeSlot_Gone {
            get {
                return ResourceManager.GetString("TimeSlot_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La plage horaire {0} est introuvable.
        /// </summary>
        internal static string TimeSlot_NotFound {
            get {
                return ResourceManager.GetString("TimeSlot_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;heure de fin ne peut pas être supérieur ou égale à {0} heures.
        /// </summary>
        internal static string TimeSlot_To_CannotBe_GreaterOrEqualThan {
            get {
                return ResourceManager.GetString("TimeSlot_To_CannotBe_GreaterOrEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;accès n&apos;est pas autorisé, votre session a peut-être expirée, ou vos droits ne sont pas suffisants.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur innatendue est survenue, renouvellez votre demande. Si l&apos;erreur persiste, contactez notre support..
        /// </summary>
        internal static string Unexpected {
            get {
                return ResourceManager.GetString("Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la mise à jour de l&apos;image de l&apos;identité du compte : {0}.
        /// </summary>
        internal static string UpdateUser_Oidc_UpdatePicture_Error {
            get {
                return ResourceManager.GetString("UpdateUser_Oidc_UpdatePicture_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la mise à jour des informations de l&apos;identité du compte : {0}.
        /// </summary>
        internal static string UpdateUser_Oidc_UpdateProfile_Error {
            get {
                return ResourceManager.GetString("UpdateUser_Oidc_UpdateProfile_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse email est requise.
        /// </summary>
        internal static string User_Email_Required {
            get {
                return ResourceManager.GetString("User_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prénom est requis.
        /// </summary>
        internal static string User_Firstname_Required {
            get {
                return ResourceManager.GetString("User_Firstname_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur {0} n&apos;est plus disponible.
        /// </summary>
        internal static string User_Gone {
            get {
                return ResourceManager.GetString("User_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;identifiant de l&apos;utilisateur est invalide.
        /// </summary>
        internal static string User_Id_Invalid {
            get {
                return ResourceManager.GetString("User_Id_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom de famille est requis.
        /// </summary>
        internal static string User_Lastname_Required {
            get {
                return ResourceManager.GetString("User_Lastname_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur {0} est introuvable.
        /// </summary>
        internal static string User_NotFound {
            get {
                return ResourceManager.GetString("User_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score utilisateur.
        /// </summary>
        internal static string UserPoints {
            get {
                return ResourceManager.GetString("UserPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le score utilisateur {0} n&apos;est plus disponible.
        /// </summary>
        internal static string UserPoints_Gone {
            get {
                return ResourceManager.GetString("UserPoints_Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le score utilisateur {0} est introuvable.
        /// </summary>
        internal static string UserPoints_NotFound {
            get {
                return ResourceManager.GetString("UserPoints_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nombre de points pour l&apos;utilisateur ne peut être inférieur ou égale à {0}.
        /// </summary>
        internal static string UserPoints_Quantity_CannotBe_LowerThan {
            get {
                return ResourceManager.GetString("UserPoints_Quantity_CannotBe_LowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La correspondance de niveau en fonction des points est introuvable.
        /// </summary>
        internal static string UserPoints_Scoring_Matching_ActionPoints_NotFound {
            get {
                return ResourceManager.GetString("UserPoints_Scoring_Matching_ActionPoints_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur pour les points est requis.
        /// </summary>
        internal static string UserPoints_User_Required {
            get {
                return ResourceManager.GetString("UserPoints_User_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les données reçues sont invalides ou invalides, veuillez vérifier les données saisies..
        /// </summary>
        internal static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
    }
}
