//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheaft.Localization.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Sheaft.Localization.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        internal static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        internal static string Gone {
            get {
                return ResourceManager.GetString("Gone", resourceCulture);
            }
        }
        
        internal static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        internal static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        internal static string Unexpected {
            get {
                return ResourceManager.GetString("Unexpected", resourceCulture);
            }
        }
        
        internal static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string Address_Line1_Required {
            get {
                return ResourceManager.GetString("Address_Line1_Required", resourceCulture);
            }
        }
        
        internal static string Address_Zipcode_Required {
            get {
                return ResourceManager.GetString("Address_Zipcode_Required", resourceCulture);
            }
        }
        
        internal static string Address_City_Required {
            get {
                return ResourceManager.GetString("Address_City_Required", resourceCulture);
            }
        }
        
        internal static string Address_Country_Required {
            get {
                return ResourceManager.GetString("Address_Country_Required", resourceCulture);
            }
        }
        
        internal static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        internal static string Agreement_SelectedHour_NotFoundInDeliveryOpeningHours {
            get {
                return ResourceManager.GetString("Agreement_SelectedHour_NotFoundInDeliveryOpeningHours", resourceCulture);
            }
        }
        
        internal static string Agreement_CannotBeAccepted_NotInWaitingStatus {
            get {
                return ResourceManager.GetString("Agreement_CannotBeAccepted_NotInWaitingStatus", resourceCulture);
            }
        }
        
        internal static string Agreement_CannotBeCancelled_AlreadyCancelled {
            get {
                return ResourceManager.GetString("Agreement_CannotBeCancelled_AlreadyCancelled", resourceCulture);
            }
        }
        
        internal static string Agreement_CannotBeCancelled_AlreadyRefused {
            get {
                return ResourceManager.GetString("Agreement_CannotBeCancelled_AlreadyRefused", resourceCulture);
            }
        }
        
        internal static string Agreement_CannotBeRefused_NotInWaitingStatus {
            get {
                return ResourceManager.GetString("Agreement_CannotBeRefused_NotInWaitingStatus", resourceCulture);
            }
        }
        
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        internal static string Store_Address_Required {
            get {
                return ResourceManager.GetString("Store_Address_Required", resourceCulture);
            }
        }
        
        internal static string Store_Name_Required {
            get {
                return ResourceManager.GetString("Store_Name_Required", resourceCulture);
            }
        }
        
        internal static string Store_Email_Required {
            get {
                return ResourceManager.GetString("Store_Email_Required", resourceCulture);
            }
        }
        
        internal static string Store_TagNotFound {
            get {
                return ResourceManager.GetString("Store_TagNotFound", resourceCulture);
            }
        }
        
        internal static string Producer {
            get {
                return ResourceManager.GetString("Producer", resourceCulture);
            }
        }
        
        internal static string Producer_Address_Required {
            get {
                return ResourceManager.GetString("Producer_Address_Required", resourceCulture);
            }
        }
        
        internal static string Producer_Name_Required {
            get {
                return ResourceManager.GetString("Producer_Name_Required", resourceCulture);
            }
        }
        
        internal static string Producer_Email_Required {
            get {
                return ResourceManager.GetString("Producer_Email_Required", resourceCulture);
            }
        }
        
        internal static string Producer_Documents_NotValidated {
            get {
                return ResourceManager.GetString("Producer_Documents_NotValidated", resourceCulture);
            }
        }
        
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        internal static string Product_Producer_Required {
            get {
                return ResourceManager.GetString("Product_Producer_Required", resourceCulture);
            }
        }
        
        internal static string Product_Reference_Required {
            get {
                return ResourceManager.GetString("Product_Reference_Required", resourceCulture);
            }
        }
        
        internal static string Product_Name_Required {
            get {
                return ResourceManager.GetString("Product_Name_Required", resourceCulture);
            }
        }
        
        internal static string Product_WholeSalePrice_CannotBe_LowerOrEqualThan {
            get {
                return ResourceManager.GetString("Product_WholeSalePrice_CannotBe_LowerOrEqualThan", resourceCulture);
            }
        }
        
        internal static string Product_Weight_CannotBe_LowerOrEqualThan {
            get {
                return ResourceManager.GetString("Product_Weight_CannotBe_LowerOrEqualThan", resourceCulture);
            }
        }
        
        internal static string Product_Vat_CannotBe_LowerThan {
            get {
                return ResourceManager.GetString("Product_Vat_CannotBe_LowerThan", resourceCulture);
            }
        }
        
        internal static string Product_Vat_CannotBe_GreaterThan {
            get {
                return ResourceManager.GetString("Product_Vat_CannotBe_GreaterThan", resourceCulture);
            }
        }
        
        internal static string Product_Description_TooLong {
            get {
                return ResourceManager.GetString("Product_Description_TooLong", resourceCulture);
            }
        }
        
        internal static string Product_QuantityPerUnit_CannotBe_LowerOrEqualThan {
            get {
                return ResourceManager.GetString("Product_QuantityPerUnit_CannotBe_LowerOrEqualThan", resourceCulture);
            }
        }
        
        internal static string Product_TagNotFound {
            get {
                return ResourceManager.GetString("Product_TagNotFound", resourceCulture);
            }
        }
        
        internal static string Product_CannotRate_AlreadyRated {
            get {
                return ResourceManager.GetString("Product_CannotRate_AlreadyRated", resourceCulture);
            }
        }
        
        internal static string Product_BulkConditioning_Requires_Unit_ToBe_Specified {
            get {
                return ResourceManager.GetString("Product_BulkConditioning_Requires_Unit_ToBe_Specified", resourceCulture);
            }
        }
        
        internal static string Consumer {
            get {
                return ResourceManager.GetString("Consumer", resourceCulture);
            }
        }
        
        internal static string Consumer_Id_Invalid {
            get {
                return ResourceManager.GetString("Consumer_Id_Invalid", resourceCulture);
            }
        }
        
        internal static string Consumer_Email_Required {
            get {
                return ResourceManager.GetString("Consumer_Email_Required", resourceCulture);
            }
        }
        
        internal static string Consumer_Firstname_Required {
            get {
                return ResourceManager.GetString("Consumer_Firstname_Required", resourceCulture);
            }
        }
        
        internal static string Consumer_Lastname_Required {
            get {
                return ResourceManager.GetString("Consumer_Lastname_Required", resourceCulture);
            }
        }
        
        internal static string Consumer_CannotBeDeleted_HasActiveOrders {
            get {
                return ResourceManager.GetString("Consumer_CannotBeDeleted_HasActiveOrders", resourceCulture);
            }
        }
        
        internal static string DeliveryMode {
            get {
                return ResourceManager.GetString("DeliveryMode", resourceCulture);
            }
        }
        
        internal static string DeliveryMode_LockOrderHoursBeforeDelivery_CannotBe_LowerThan {
            get {
                return ResourceManager.GetString("DeliveryMode_LockOrderHoursBeforeDelivery_CannotBe_LowerThan", resourceCulture);
            }
        }
        
        internal static string DeliveryMode_CannotRemove_With_Active_Agreements {
            get {
                return ResourceManager.GetString("DeliveryMode_CannotRemove_With_Active_Agreements", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_Vendor_Required {
            get {
                return ResourceManager.GetString("PurchaseOrder_Vendor_Required", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_Sender_Required {
            get {
                return ResourceManager.GetString("PurchaseOrder_Sender_Required", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_Reference_Required {
            get {
                return ResourceManager.GetString("PurchaseOrder_Reference_Required", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotAccept_NotIn_WaitingStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotAccept_NotIn_WaitingStatus", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotComplete_NotIn_ProcessingStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotComplete_NotIn_ProcessingStatus", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotShip_NotIn_CompletedStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotShip_NotIn_CompletedStatus", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotDeliver_NotIn_CompletedOrShippingStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotDeliver_NotIn_CompletedOrShippingStatus", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotCancel_AlreadyIn_CancelledStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotCancel_AlreadyIn_CancelledStatus", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotCancel_AlreadyIn_RefusedStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotCancel_AlreadyIn_RefusedStatus", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotCancel_AlreadyIn_DeliveredStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotCancel_AlreadyIn_DeliveredStatus", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotRefuse_AlreadyIn_CancelledStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotRefuse_AlreadyIn_CancelledStatus", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotRefuse_AlreadyIn_RefusedStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotRefuse_AlreadyIn_RefusedStatus", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotRefuse_AlreadyIn_DeliveredStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotRefuse_AlreadyIn_DeliveredStatus", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotAddProduct_NotIn_WaitingStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotAddProduct_NotIn_WaitingStatus", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotAddProduct_Product_NotFound {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotAddProduct_Product_NotFound", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotChangeProductQuantity_NotIn_WaitingStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotChangeProductQuantity_NotIn_WaitingStatus", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotChangeProductQuantity_Product_NotFound {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotChangeProductQuantity_Product_NotFound", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotRemoveProduct_NotIn_WaitingStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotRemoveProduct_NotIn_WaitingStatus", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotRemoveProduct_Product_NotFound {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotRemoveProduct_Product_NotFound", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_ProductQuantity_CannotBe_LowerOrEqualThan {
            get {
                return ResourceManager.GetString("PurchaseOrder_ProductQuantity_CannotBe_LowerOrEqualThan", resourceCulture);
            }
        }
        
        internal static string PurchaseOrder_CannotSet_Transfer_AlreadySucceeded {
            get {
                return ResourceManager.GetString("PurchaseOrder_CannotSet_Transfer_AlreadySucceeded", resourceCulture);
            }
        }
        
        internal static string ExpectedDelivery {
            get {
                return ResourceManager.GetString("ExpectedDelivery", resourceCulture);
            }
        }
        
        internal static string ExpectedDelivery_ExpectedDate_CannotBe_BeforeNow {
            get {
                return ResourceManager.GetString("ExpectedDelivery_ExpectedDate_CannotBe_BeforeNow", resourceCulture);
            }
        }
        
        internal static string ExpectedDelivery_ExpectedDate_NotIn_DeliveryOpeningHours {
            get {
                return ResourceManager.GetString("ExpectedDelivery_ExpectedDate_NotIn_DeliveryOpeningHours", resourceCulture);
            }
        }
        
        internal static string ExpectedDelivery_ExpectedDate_OrdersLocked {
            get {
                return ResourceManager.GetString("ExpectedDelivery_ExpectedDate_OrdersLocked", resourceCulture);
            }
        }
        
        internal static string ExpectedDelivery_ExpectedDate_DeliveryRemoved {
            get {
                return ResourceManager.GetString("ExpectedDelivery_ExpectedDate_DeliveryRemoved", resourceCulture);
            }
        }
        
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        internal static string Level_Name_Required {
            get {
                return ResourceManager.GetString("Level_Name_Required", resourceCulture);
            }
        }
        
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        internal static string Notification_Require_Content {
            get {
                return ResourceManager.GetString("Notification_Require_Content", resourceCulture);
            }
        }
        
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        internal static string Job_Name_Required {
            get {
                return ResourceManager.GetString("Job_Name_Required", resourceCulture);
            }
        }
        
        internal static string Job_Queue_Required {
            get {
                return ResourceManager.GetString("Job_Queue_Required", resourceCulture);
            }
        }
        
        internal static string Job_User_Required {
            get {
                return ResourceManager.GetString("Job_User_Required", resourceCulture);
            }
        }
        
        internal static string Job_CannotRetry_NotIn_CanncelledOrFailedStatus {
            get {
                return ResourceManager.GetString("Job_CannotRetry_NotIn_CanncelledOrFailedStatus", resourceCulture);
            }
        }
        
        internal static string Job_CannotPause_NotIn_ProcessingStatus {
            get {
                return ResourceManager.GetString("Job_CannotPause_NotIn_ProcessingStatus", resourceCulture);
            }
        }
        
        internal static string Job_CannotArchive_NotIn_TerminatedStatus {
            get {
                return ResourceManager.GetString("Job_CannotArchive_NotIn_TerminatedStatus", resourceCulture);
            }
        }
        
        internal static string Job_CannotResume_NotIn_PausedStatus {
            get {
                return ResourceManager.GetString("Job_CannotResume_NotIn_PausedStatus", resourceCulture);
            }
        }
        
        internal static string Job_CannotComplete_NotIn_ProcessingStatus {
            get {
                return ResourceManager.GetString("Job_CannotComplete_NotIn_ProcessingStatus", resourceCulture);
            }
        }
        
        internal static string Job_CannotCancel_AlreadyDone {
            get {
                return ResourceManager.GetString("Job_CannotCancel_AlreadyDone", resourceCulture);
            }
        }
        
        internal static string Job_CannotCancel_AlreadyCancelled {
            get {
                return ResourceManager.GetString("Job_CannotCancel_AlreadyCancelled", resourceCulture);
            }
        }
        
        internal static string Job_CannotFail_AlreadyDone {
            get {
                return ResourceManager.GetString("Job_CannotFail_AlreadyDone", resourceCulture);
            }
        }
        
        internal static string Job_CannotFail_AlreadyCancelled {
            get {
                return ResourceManager.GetString("Job_CannotFail_AlreadyCancelled", resourceCulture);
            }
        }
        
        internal static string Job_Command_Required {
            get {
                return ResourceManager.GetString("Job_Command_Required", resourceCulture);
            }
        }
        
        internal static string Job_CannotStart_Has_StartedOnDate {
            get {
                return ResourceManager.GetString("Job_CannotStart_Has_StartedOnDate", resourceCulture);
            }
        }
        
        internal static string Job_CannotStart_NotIn_WaitingStatus {
            get {
                return ResourceManager.GetString("Job_CannotStart_NotIn_WaitingStatus", resourceCulture);
            }
        }
        
        internal static string Returnable {
            get {
                return ResourceManager.GetString("Returnable", resourceCulture);
            }
        }
        
        internal static string Returnable_WholeSalePrice_CannotBe_LowerThan {
            get {
                return ResourceManager.GetString("Returnable_WholeSalePrice_CannotBe_LowerThan", resourceCulture);
            }
        }
        
        internal static string Returnable_Vat_CannotBe_LowerThan {
            get {
                return ResourceManager.GetString("Returnable_Vat_CannotBe_LowerThan", resourceCulture);
            }
        }
        
        internal static string Returnable_Vat_CannotBe_GreaterThan {
            get {
                return ResourceManager.GetString("Returnable_Vat_CannotBe_GreaterThan", resourceCulture);
            }
        }
        
        internal static string Returnable_Name_Required {
            get {
                return ResourceManager.GetString("Returnable_Name_Required", resourceCulture);
            }
        }
        
        internal static string QuickOrder {
            get {
                return ResourceManager.GetString("QuickOrder", resourceCulture);
            }
        }
        
        internal static string QuickOrder_ProductQuantity_CannotBe_LowerOrEqualThan {
            get {
                return ResourceManager.GetString("QuickOrder_ProductQuantity_CannotBe_LowerOrEqualThan", resourceCulture);
            }
        }
        
        internal static string QuickOrder_User_Required {
            get {
                return ResourceManager.GetString("QuickOrder_User_Required", resourceCulture);
            }
        }
        
        internal static string QuickOrder_Name_Required {
            get {
                return ResourceManager.GetString("QuickOrder_Name_Required", resourceCulture);
            }
        }
        
        internal static string QuickOrder_CannotAddProduct_Product_AlreadyIn {
            get {
                return ResourceManager.GetString("QuickOrder_CannotAddProduct_Product_AlreadyIn", resourceCulture);
            }
        }
        
        internal static string QuickOrder_CannotRemoveProduct_Product_NotFound {
            get {
                return ResourceManager.GetString("QuickOrder_CannotRemoveProduct_Product_NotFound", resourceCulture);
            }
        }
        
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        internal static string Rating_User_Required {
            get {
                return ResourceManager.GetString("Rating_User_Required", resourceCulture);
            }
        }
        
        internal static string Rating_CannotBe_GreatherThan {
            get {
                return ResourceManager.GetString("Rating_CannotBe_GreatherThan", resourceCulture);
            }
        }
        
        internal static string Rating_CannotBe_LowerThan {
            get {
                return ResourceManager.GetString("Rating_CannotBe_LowerThan", resourceCulture);
            }
        }
        
        internal static string Reward {
            get {
                return ResourceManager.GetString("Reward", resourceCulture);
            }
        }
        
        internal static string Reward_Name_Required {
            get {
                return ResourceManager.GetString("Reward_Name_Required", resourceCulture);
            }
        }
        
        internal static string Sponsoring {
            get {
                return ResourceManager.GetString("Sponsoring", resourceCulture);
            }
        }
        
        internal static string Sponsoring_Sponsor_Required {
            get {
                return ResourceManager.GetString("Sponsoring_Sponsor_Required", resourceCulture);
            }
        }
        
        internal static string Sponsoring_Sponsored_Required {
            get {
                return ResourceManager.GetString("Sponsoring_Sponsored_Required", resourceCulture);
            }
        }
        
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        internal static string Tag_Name_Required {
            get {
                return ResourceManager.GetString("Tag_Name_Required", resourceCulture);
            }
        }
        
        internal static string TimeSlot {
            get {
                return ResourceManager.GetString("TimeSlot", resourceCulture);
            }
        }
        
        internal static string TimeSlot_From_CannotBe_GreaterOrEqualThan {
            get {
                return ResourceManager.GetString("TimeSlot_From_CannotBe_GreaterOrEqualThan", resourceCulture);
            }
        }
        
        internal static string TimeSlot_To_CannotBe_GreaterOrEqualThan {
            get {
                return ResourceManager.GetString("TimeSlot_To_CannotBe_GreaterOrEqualThan", resourceCulture);
            }
        }
        
        internal static string TimeSlot_From_CannotBe_GreaterOrEqualThan_To {
            get {
                return ResourceManager.GetString("TimeSlot_From_CannotBe_GreaterOrEqualThan_To", resourceCulture);
            }
        }
        
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        internal static string Points_Quantity_CannotBe_LowerThan {
            get {
                return ResourceManager.GetString("Points_Quantity_CannotBe_LowerThan", resourceCulture);
            }
        }
        
        internal static string Points_User_Required {
            get {
                return ResourceManager.GetString("Points_User_Required", resourceCulture);
            }
        }
        
        internal static string Points_Scoring_Matching_ActionPoints_NotFound {
            get {
                return ResourceManager.GetString("Points_Scoring_Matching_ActionPoints_NotFound", resourceCulture);
            }
        }
        
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        internal static string Order_Total_CannotBe_LowerThan {
            get {
                return ResourceManager.GetString("Order_Total_CannotBe_LowerThan", resourceCulture);
            }
        }
        
        internal static string Order_CannotCreate_Some_Products_NotAvailable {
            get {
                return ResourceManager.GetString("Order_CannotCreate_Some_Products_NotAvailable", resourceCulture);
            }
        }
        
        internal static string Order_CannotUpdate_Some_Products_NotAvailable {
            get {
                return ResourceManager.GetString("Order_CannotUpdate_Some_Products_NotAvailable", resourceCulture);
            }
        }
        
        internal static string Order_CannotPay_Some_Products_NotAvailable {
            get {
                return ResourceManager.GetString("Order_CannotPay_Some_Products_NotAvailable", resourceCulture);
            }
        }
        
        internal static string Order_CannotCreate_Some_Products_Closed {
            get {
                return ResourceManager.GetString("Order_CannotCreate_Some_Products_Closed", resourceCulture);
            }
        }
        
        internal static string Order_CannotUpdate_Some_Products_Closed {
            get {
                return ResourceManager.GetString("Order_CannotUpdate_Some_Products_Closed", resourceCulture);
            }
        }
        
        internal static string Order_CannotPay_Some_Products_Closed {
            get {
                return ResourceManager.GetString("Order_CannotPay_Some_Products_Closed", resourceCulture);
            }
        }
        
        internal static string Order_CannotCreate_Some_Delivery_Closed {
            get {
                return ResourceManager.GetString("Order_CannotCreate_Some_Delivery_Closed", resourceCulture);
            }
        }
        
        internal static string Order_CannotUpdate_Some_Delivery_Closed {
            get {
                return ResourceManager.GetString("Order_CannotUpdate_Some_Delivery_Closed", resourceCulture);
            }
        }
        
        internal static string Order_CannotPay_Some_Delivery_Closed {
            get {
                return ResourceManager.GetString("Order_CannotPay_Some_Delivery_Closed", resourceCulture);
            }
        }
        
        internal static string Order_CannotCreate_Some_Producer_Closed {
            get {
                return ResourceManager.GetString("Order_CannotCreate_Some_Producer_Closed", resourceCulture);
            }
        }
        
        internal static string Order_CannotUpdate_Some_Producer_Closed {
            get {
                return ResourceManager.GetString("Order_CannotUpdate_Some_Producer_Closed", resourceCulture);
            }
        }
        
        internal static string Order_CannotPay_Some_Producer_Closed {
            get {
                return ResourceManager.GetString("Order_CannotPay_Some_Producer_Closed", resourceCulture);
            }
        }
        
        internal static string Order_CannotCreate_Deliveries_Required {
            get {
                return ResourceManager.GetString("Order_CannotCreate_Deliveries_Required", resourceCulture);
            }
        }
        
        internal static string Order_CannotPay_Deliveries_Required {
            get {
                return ResourceManager.GetString("Order_CannotPay_Deliveries_Required", resourceCulture);
            }
        }
        
        internal static string Order_CannotRetry_NotIn_Refused_Status {
            get {
                return ResourceManager.GetString("Order_CannotRetry_NotIn_Refused_Status", resourceCulture);
            }
        }
        
        internal static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        internal static string Legal_Siret_Required {
            get {
                return ResourceManager.GetString("Legal_Siret_Required", resourceCulture);
            }
        }
        
        internal static string Legal_Vat_Required {
            get {
                return ResourceManager.GetString("Legal_Vat_Required", resourceCulture);
            }
        }
        
        internal static string Legal_Kind_Cannot_Be_Natural {
            get {
                return ResourceManager.GetString("Legal_Kind_Cannot_Be_Natural", resourceCulture);
            }
        }
        
        internal static string Legal_Email_Required {
            get {
                return ResourceManager.GetString("Legal_Email_Required", resourceCulture);
            }
        }
        
        internal static string Payin {
            get {
                return ResourceManager.GetString("Payin", resourceCulture);
            }
        }
        
        internal static string Payin_CannotSet_Already_Succeeded {
            get {
                return ResourceManager.GetString("Payin_CannotSet_Already_Succeeded", resourceCulture);
            }
        }
        
        internal static string Payin_CannotAdd_Refund_PurchaseOrderRefund_AlreadySucceeded {
            get {
                return ResourceManager.GetString("Payin_CannotAdd_Refund_PurchaseOrderRefund_AlreadySucceeded", resourceCulture);
            }
        }
        
        internal static string Payin_CannotCreate_Order_Already_Validated {
            get {
                return ResourceManager.GetString("Payin_CannotCreate_Order_Already_Validated", resourceCulture);
            }
        }
        
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        internal static string Transfer_CannotCreate_PurchaseOrder_Invalid_Status {
            get {
                return ResourceManager.GetString("Transfer_CannotCreate_PurchaseOrder_Invalid_Status", resourceCulture);
            }
        }
        
        internal static string Transfer_CannotCreate_Pending_Transfer {
            get {
                return ResourceManager.GetString("Transfer_CannotCreate_Pending_Transfer", resourceCulture);
            }
        }
        
        internal static string Payout {
            get {
                return ResourceManager.GetString("Payout", resourceCulture);
            }
        }
        
        internal static string Ubo {
            get {
                return ResourceManager.GetString("Ubo", resourceCulture);
            }
        }
        
        internal static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        internal static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        internal static string Donation_CannotSet_Already_Succeeded {
            get {
                return ResourceManager.GetString("Donation_CannotSet_Already_Succeeded", resourceCulture);
            }
        }
        
        internal static string Donation_CannotCreate_AlreadySucceeded {
            get {
                return ResourceManager.GetString("Donation_CannotCreate_AlreadySucceeded", resourceCulture);
            }
        }
        
        internal static string Donation_CannotCreate_PendingDonation {
            get {
                return ResourceManager.GetString("Donation_CannotCreate_PendingDonation", resourceCulture);
            }
        }
        
        internal static string PayinRefund {
            get {
                return ResourceManager.GetString("PayinRefund", resourceCulture);
            }
        }
        
        internal static string PayinRefund_CannotCreate_Payin_PurchaseOrder_Invalid_Status {
            get {
                return ResourceManager.GetString("PayinRefund_CannotCreate_Payin_PurchaseOrder_Invalid_Status", resourceCulture);
            }
        }
        
        internal static string PayinRefund_CannotCreate_PurchaseOrderRefund_Payin_Invalid_Status {
            get {
                return ResourceManager.GetString("PayinRefund_CannotCreate_PurchaseOrderRefund_Payin_Invalid_Status", resourceCulture);
            }
        }
        
        internal static string PayinRefund_CannotCreate_PurchaseOrderRefund_Pending_PayinRefund {
            get {
                return ResourceManager.GetString("PayinRefund_CannotCreate_PurchaseOrderRefund_Pending_PayinRefund", resourceCulture);
            }
        }
        
        internal static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        internal static string Declaration {
            get {
                return ResourceManager.GetString("Declaration", resourceCulture);
            }
        }
        
        internal static string Declaration_CannotSubmit_NotLocked {
            get {
                return ResourceManager.GetString("Declaration_CannotSubmit_NotLocked", resourceCulture);
            }
        }
        
        internal static string Declaration_NotValidated {
            get {
                return ResourceManager.GetString("Declaration_NotValidated", resourceCulture);
            }
        }
        
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        internal static string Document_CannotCreate_Type_Already_Present {
            get {
                return ResourceManager.GetString("Document_CannotCreate_Type_Already_Present", resourceCulture);
            }
        }
        
        internal static string Document_CannotUpdate_Another_Document_With_Type_Exists {
            get {
                return ResourceManager.GetString("Document_CannotUpdate_Another_Document_With_Type_Exists", resourceCulture);
            }
        }
        
        internal static string Document_CannotSubmit_NotLocked {
            get {
                return ResourceManager.GetString("Document_CannotSubmit_NotLocked", resourceCulture);
            }
        }
        
        internal static string Document_Errors_On_Submit {
            get {
                return ResourceManager.GetString("Document_Errors_On_Submit", resourceCulture);
            }
        }
        
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        internal static string Owner_Email_Required {
            get {
                return ResourceManager.GetString("Owner_Email_Required", resourceCulture);
            }
        }
        
        internal static string Owner_Firstname_Required {
            get {
                return ResourceManager.GetString("Owner_Firstname_Required", resourceCulture);
            }
        }
        
        internal static string Owner_Lastname_Required {
            get {
                return ResourceManager.GetString("Owner_Lastname_Required", resourceCulture);
            }
        }
        
        internal static string Owner_Birthdate_Required {
            get {
                return ResourceManager.GetString("Owner_Birthdate_Required", resourceCulture);
            }
        }
        
        internal static string Owner_CountryOfResidence_Required {
            get {
                return ResourceManager.GetString("Owner_CountryOfResidence_Required", resourceCulture);
            }
        }
        
        internal static string Owner_Nationality_Required {
            get {
                return ResourceManager.GetString("Owner_Nationality_Required", resourceCulture);
            }
        }
        
        internal static string Owner_Address_Required {
            get {
                return ResourceManager.GetString("Owner_Address_Required", resourceCulture);
            }
        }
        
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        internal static string User_Address_Required {
            get {
                return ResourceManager.GetString("User_Address_Required", resourceCulture);
            }
        }
        
        internal static string User_Email_Required {
            get {
                return ResourceManager.GetString("User_Email_Required", resourceCulture);
            }
        }
        
        internal static string User_Firstname_Required {
            get {
                return ResourceManager.GetString("User_Firstname_Required", resourceCulture);
            }
        }
        
        internal static string User_Lastname_Required {
            get {
                return ResourceManager.GetString("User_Lastname_Required", resourceCulture);
            }
        }
        
        internal static string User_Name_Required {
            get {
                return ResourceManager.GetString("User_Name_Required", resourceCulture);
            }
        }
        
        internal static string User_TagNotFound {
            get {
                return ResourceManager.GetString("User_TagNotFound", resourceCulture);
            }
        }
        
        internal static string Register_User_SponsorCode_NotFound {
            get {
                return ResourceManager.GetString("Register_User_SponsorCode_NotFound", resourceCulture);
            }
        }
        
        internal static string Register_User_AlreadyExists {
            get {
                return ResourceManager.GetString("Register_User_AlreadyExists", resourceCulture);
            }
        }
        
        internal static string EmailProvider_SendEmail_Failure {
            get {
                return ResourceManager.GetString("EmailProvider_SendEmail_Failure", resourceCulture);
            }
        }
        
        internal static string CreateProduct_Name_Required_Line {
            get {
                return ResourceManager.GetString("CreateProduct_Name_Required_Line", resourceCulture);
            }
        }
        
        internal static string CreateProduct_WholeSalePrice_Invalid_Line {
            get {
                return ResourceManager.GetString("CreateProduct_WholeSalePrice_Invalid_Line", resourceCulture);
            }
        }
        
        internal static string CreateProduct_Vat_Invalid_Line {
            get {
                return ResourceManager.GetString("CreateProduct_Vat_Invalid_Line", resourceCulture);
            }
        }
        
        internal static string CreateProduct_QtyPerUnit_Invalid_Line {
            get {
                return ResourceManager.GetString("CreateProduct_QtyPerUnit_Invalid_Line", resourceCulture);
            }
        }
        
        internal static string CreateProduct_Conditioning_Invalid_Line {
            get {
                return ResourceManager.GetString("CreateProduct_Conditioning_Invalid_Line", resourceCulture);
            }
        }
        
        internal static string CreateProduct_UnitKind_Invalid_Line {
            get {
                return ResourceManager.GetString("CreateProduct_UnitKind_Invalid_Line", resourceCulture);
            }
        }
        
        internal static string CreateProduct_Reference_AlreadyExists {
            get {
                return ResourceManager.GetString("CreateProduct_Reference_AlreadyExists", resourceCulture);
            }
        }
        
        internal static string ImportProduct_Missing_Tab {
            get {
                return ResourceManager.GetString("ImportProduct_Missing_Tab", resourceCulture);
            }
        }
        
        internal static string ImportProduct_Reference_AlreadyExists {
            get {
                return ResourceManager.GetString("ImportProduct_Reference_AlreadyExists", resourceCulture);
            }
        }
        
        internal static string Identifier_Uuid_Error {
            get {
                return ResourceManager.GetString("Identifier_Uuid_Error", resourceCulture);
            }
        }
        
        internal static string Identifier_SponsorCode_Error {
            get {
                return ResourceManager.GetString("Identifier_SponsorCode_Error", resourceCulture);
            }
        }
        
        internal static string Oidc_Register_Error {
            get {
                return ResourceManager.GetString("Oidc_Register_Error", resourceCulture);
            }
        }
        
        internal static string Oidc_DeleteProfile_Error {
            get {
                return ResourceManager.GetString("Oidc_DeleteProfile_Error", resourceCulture);
            }
        }
        
        internal static string Oidc_UpdatePicture_Error {
            get {
                return ResourceManager.GetString("Oidc_UpdatePicture_Error", resourceCulture);
            }
        }
        
        internal static string Oidc_UpdateProfile_Error {
            get {
                return ResourceManager.GetString("Oidc_UpdateProfile_Error", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Wallet_User_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Wallet_User_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Wallet_Wallet_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Wallet_Wallet_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Transfer_User_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Transfer_User_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Transfer_BankIBAN_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Transfer_BankIBAN_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Card_User_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Card_User_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Card_Card_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Card_Card_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotValidate_Card_Card_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotValidate_Card_Card_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Document_User_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Document_User_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Document_Document_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Document_Document_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_DocumentPage_Document_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_DocumentPage_Document_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotSubmit_Document_User_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotSubmit_Document_User_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotSubmit_Document_Document_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotSubmit_Document_Document_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_WebPayin_TransactionKind_Mismatch {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_WebPayin_TransactionKind_Mismatch", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_WebPayin_TransactionNature_Mismatch {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_WebPayin_TransactionNature_Mismatch", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_WebPayin_Author_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_WebPayin_Author_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_WebPayin_CreditedWallet_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_WebPayin_CreditedWallet_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Transfer_TransactionKind_Mismatch {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Transfer_TransactionKind_Mismatch", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Transfer_TransactionNature_Mismatch {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Transfer_TransactionNature_Mismatch", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Transfer_Author_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Transfer_Author_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Transfer_CreditedWallet_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Transfer_CreditedWallet_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Transfer_DebitedWallet_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Transfer_DebitedWallet_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Payout_TransactionKind_Mismatch {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Payout_TransactionKind_Mismatch", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Payout_TransactionNature_Mismatch {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Payout_TransactionNature_Mismatch", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Payout_Author_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Payout_Author_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Payout_DebitedWallet_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Payout_DebitedWallet_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotRefund_Payin_TransactionKind_Mismatch {
            get {
                return ResourceManager.GetString("PsP_CannotRefund_Payin_TransactionKind_Mismatch", resourceCulture);
            }
        }
        
        internal static string PsP_CannotRefund_Payin_TransactionNature_Mismatch {
            get {
                return ResourceManager.GetString("PsP_CannotRefund_Payin_TransactionNature_Mismatch", resourceCulture);
            }
        }
        
        internal static string PsP_CannotRefund_Payin_Author_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotRefund_Payin_Author_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotRefund_Payin_PayinIdentifier_Missing {
            get {
                return ResourceManager.GetString("PsP_CannotRefund_Payin_PayinIdentifier_Missing", resourceCulture);
            }
        }
        
        internal static string PsP_CannotRefund_Transfer_TransactionKind_Mismatch {
            get {
                return ResourceManager.GetString("PsP_CannotRefund_Transfer_TransactionKind_Mismatch", resourceCulture);
            }
        }
        
        internal static string PsP_CannotRefund_Transfer_TransactionNature_Mismatch {
            get {
                return ResourceManager.GetString("PsP_CannotRefund_Transfer_TransactionNature_Mismatch", resourceCulture);
            }
        }
        
        internal static string PsP_CannotRefund_Transfer_Author_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotRefund_Transfer_Author_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotRefund_Transfer_TransferIdentifier_Missing {
            get {
                return ResourceManager.GetString("PsP_CannotRefund_Transfer_TransferIdentifier_Missing", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Declaration_User_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Declaration_User_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotUpdate_Declaration_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotUpdate_Declaration_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotSubmit_Declaration_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotSubmit_Declaration_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotAddUbo_Declaration_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotAddUbo_Declaration_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotUpdateUbo_Declaration_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotUpdateUbo_Declaration_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotUpdateUbo_Ubo_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotUpdateUbo_Ubo_Not_Exists", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_User_User_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_User_User_Exists", resourceCulture);
            }
        }
        
        internal static string Legal_Cannot_Unrequire_Declaration {
            get {
                return ResourceManager.GetString("Legal_Cannot_Unrequire_Declaration", resourceCulture);
            }
        }
        
        internal static string Transfer_CannotCreate_AlreadyProcessed {
            get {
                return ResourceManager.GetString("Transfer_CannotCreate_AlreadyProcessed", resourceCulture);
            }
        }
        
        internal static string PayinRefund_CannotCreate_PurchaseOrderRefund_PayinRefund_AlreadyProcessed {
            get {
                return ResourceManager.GetString("PayinRefund_CannotCreate_PurchaseOrderRefund_PayinRefund_AlreadyProcessed", resourceCulture);
            }
        }
        
        internal static string Product_Vat_Required {
            get {
                return ResourceManager.GetString("Product_Vat_Required", resourceCulture);
            }
        }
        
        internal static string Product_Conditioning_Required {
            get {
                return ResourceManager.GetString("Product_Conditioning_Required", resourceCulture);
            }
        }
        
        internal static string Legal_Name_Required {
            get {
                return ResourceManager.GetString("Legal_Name_Required", resourceCulture);
            }
        }
        
        internal static string PsP_CannotCreate_Payout_BankAccount_Not_Exists {
            get {
                return ResourceManager.GetString("PsP_CannotCreate_Payout_BankAccount_Not_Exists", resourceCulture);
            }
        }
        
        internal static string Payout_CannotCreate_User_NotValidated {
            get {
                return ResourceManager.GetString("Payout_CannotCreate_User_NotValidated", resourceCulture);
            }
        }
        
        internal static string Legal_Kind_Must_Be_Natural {
            get {
                return ResourceManager.GetString("Legal_Kind_Must_Be_Natural", resourceCulture);
            }
        }
        
        internal static string Withholding {
            get {
                return ResourceManager.GetString("Withholding", resourceCulture);
            }
        }
        
        internal static string Withholding_Cannot_Process_Already_Succeeded {
            get {
                return ResourceManager.GetString("Withholding_Cannot_Process_Already_Succeeded", resourceCulture);
            }
        }
        
        internal static string Withholding_Cannot_Process_Payout_No_Withholdings {
            get {
                return ResourceManager.GetString("Withholding_Cannot_Process_Payout_No_Withholdings", resourceCulture);
            }
        }
        
        internal static string Withholding_Cannot_Process_Pending {
            get {
                return ResourceManager.GetString("Withholding_Cannot_Process_Pending", resourceCulture);
            }
        }
        
        internal static string Order_CannotPay_Delivery_Max_PurchaseOrders_Reached {
            get {
                return ResourceManager.GetString("Order_CannotPay_Delivery_Max_PurchaseOrders_Reached", resourceCulture);
            }
        }
        
        internal static string Unauthenticated {
            get {
                return ResourceManager.GetString("Unauthenticated", resourceCulture);
            }
        }
    }
}
