version: "3.8"
services:
  sql:
    container_name: sql-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - ./docker.env
    ports:
      - "1434:1433"
    networks:
      sheaft_net:
        ipv4_address: 172.28.1.10
        aliases:
          - db-svc
    environment:
      ACCEPT_EULA: "Y"
  identity:
    image: sheaft/sheaft.identity:latest
    container_name: identity
    env_file:
      - ./docker.env
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      sheaft_net:
        ipv4_address: 172.28.1.2
        aliases:
          - identity-svc
    depends_on:
      - sql
    environment:
        ASPNETCORE_NEW_RELIC_APP_NAME: "IDENTITY-DEV"
  graphql:
    image: sheaft/sheaft.graphql:latest
    container_name: graphql
    env_file:
      - ./docker.env
    ports:
      - "5002:80"
      - "5003:443"
    networks:
      sheaft_net:
        ipv4_address: 172.28.1.3
        aliases:
          - graphql-svc
    depends_on:
      - sql
      - identity
    environment:
        ASPNETCORE_NEW_RELIC_APP_NAME: "GRAPHQL-DEV"
  jobs:
    image: sheaft/sheaft.jobs:latest
    container_name: jobs
    env_file:
      - ./docker.env
    ports:
      - "5021:80"
      - "5020:443"
    networks:
      sheaft_net:
        ipv4_address: 172.28.1.4
        aliases:
          - jobs-svc
    depends_on:
      - graphql
      - identity
    environment:
        ASPNETCORE_NEW_RELIC_APP_NAME: "JOBS-DEV"
  manage:
    image: sheaft/sheaft.manage:latest
    container_name: manage
    env_file:
      - ./docker.env
    ports:
      - "5007:80"
      - "5008:443"
    networks:
      sheaft_net:
        ipv4_address: 172.28.1.5
        aliases:
          - manage-svc
    depends_on:
      - graphql
      - identity
    environment:
        ASPNETCORE_NEW_RELIC_APP_NAME: "MANAGE-DEV"
  signalr:
    image: sheaft/sheaft.signalr:latest
    container_name: signalr
    env_file:
      - ./docker.env
    ports:
      - "5009:80"
      - "5010:443"
    networks:
      sheaft_net:
        ipv4_address: 172.28.1.6
        aliases:
          - signalr-svc
    depends_on:
      - graphql
      - identity
    environment:
        ASPNETCORE_NEW_RELIC_APP_NAME: "SIGNALR-DEV"
  payment:
    image: sheaft/sheaft.payment:latest
    container_name: payment
    env_file:
      - ./docker.env
    ports:
      - "5014:80"
      - "5015:443"
    networks:
      sheaft_net:
        ipv4_address: 172.28.1.7
        aliases:
          - payment-svc
    depends_on:
      - graphql
      - jobs
    environment:
        ASPNETCORE_NEW_RELIC_APP_NAME: "PAYMENT-DEV"

networks:
  sheaft_net:
    ipam:
      config:
        - subnet: 172.28.1.0/24