api:
  url: https://status.sheaft.com/api/v1
  token: ######
  insecure: false
date_format: 02/01/2006 15:04:05 MST
monitors:
  - name: API GraphQL
    target: https://api.sheaft.com/health/livez
    strict: true
    method: GET    
    component_id: 3
    metric_id: 1
    template:
      investigating:
        subject: "Service {{ .Monitor.Name }} injoignable"
        message: "La vérification de fonctionnement du service '{{ .Monitor.Name }}' a échouée à {{ .now }})\n\nRaison: {{ .FailReason }}"
      fixed:
        subject: "Service {{ .Monitor.Name }} rétabli" 
        message: "Le service '{{ .Monitor.Name }}' répond de nouveau aux solicitations à {{ .now }})"  
    interval: 300
    timeout: 10
    threshold: 80
    expected_status_code: 200
    expected_body: "OK"
  - name: Tâches de fond
    target: https://jobs.sheaft.com/health/livez
    strict: true
    method: GET    
    component_id: 4
    metric_id: 2
    template:
      investigating:
        subject: "Service {{ .Monitor.Name }} injoignable"
        message: "La vérification de fonctionnement du service '{{ .Monitor.Name }}' a échouée à {{ .now }})\n\nRaison: {{ .FailReason }}"
      fixed:
        subject: "Service {{ .Monitor.Name }} rétabli"   
        message: "Le service '{{ .Monitor.Name }}' répond de nouveau aux solicitations à {{ .now }})" 
    interval: 300
    timeout: 10
    threshold: 80
    expected_status_code: 200
    expected_body: "OK"
  - name: Notifications de Paiement
    target: https://payment.sheaft.com/health/livez
    strict: true
    method: GET    
    component_id: 5
    metric_id: 3
    template:
      investigating:
        subject: "Service {{ .Monitor.Name }} injoignable"
        message: "La vérification de fonctionnement du service '{{ .Monitor.Name }}' a échouée à {{ .now }})\n\nRaison: {{ .FailReason }}"
      fixed:
        subject: "Service {{ .Monitor.Name }} rétabli" 
        message: "Le service '{{ .Monitor.Name }}' répond de nouveau aux solicitations à {{ .now }})" 
    interval: 300
    timeout: 10
    threshold: 80
    expected_status_code: 200
    expected_body: "OK"
  - name: Notifications Web
    target: https://signalr.sheaft.com/health/livez
    strict: true
    method: GET    
    component_id: 6
    metric_id: 4
    template:
      investigating:
        subject: "Service {{ .Monitor.Name }} injoignable"
        message: "La vérification de fonctionnement du service '{{ .Monitor.Name }}' a échouée à {{ .now }})\n\nRaison: {{ .FailReason }}"
      fixed:
        subject: "Service {{ .Monitor.Name }} rétabli"  
        message: "Le service '{{ .Monitor.Name }}' répond de nouveau aux solicitations à {{ .now }})" 
    interval: 300
    timeout: 10
    threshold: 80
    expected_status_code: 200
    expected_body: "OK"    
  - name: Authentification
    target: https://auth.sheaft.com/health/livez
    strict: true
    method: GET    
    component_id: 13
    metric_id: 5
    template:
      investigating:
        subject: "Service {{ .Monitor.Name }} injoignable"
        message: "La vérification de fonctionnement du service '{{ .Monitor.Name }}' a échouée à {{ .now }})\n\nRaison: {{ .FailReason }}"
      fixed:
        subject: "Service {{ .Monitor.Name }} rétabli" 
        message: "Le service '{{ .Monitor.Name }}' répond de nouveau aux solicitations à {{ .now }})" 
    interval: 300
    timeout: 10
    threshold: 80
    expected_status_code: 200
    expected_body: "OK"